# SPDX-FileCopyrightText: 2023 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build: ⬆️"
      prefix-development: "build: ⬆️ [dev]"
    labels:
      - "ci"
      - "github_actions"
      - "dependencies"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build: ⬆️"
      prefix-development: "build: ⬆️ [dev]"
    labels:
      - "ci"
      - "github_actions"
      - "dependencies"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build: ⬆️"
      prefix-development: "build: ⬆️ [dev]"
    labels:
      - "documentation"
      - "dependencies"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 99
    commit-message:
      prefix: "build: ⬆️"
      prefix-development: "build: ⬆️ [dev]"
    allow:
      - dependency-type: "all"
    labels:
      - "python"
      - "build"
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build: ⬆️"
      prefix-development: "build: ⬆️ [dev]"
    labels:
      - "container"
      - "dependencies"
