# SPDX-FileCopyrightText: 2023 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT
#
name: Pull request
description: Create a report to help us improve
title: "bug:"
labels: ["bug"]
assignees: []

# Description

body:
  - type: input
    id: what-does-it-fix
    attributes:
      label: Which issue does it fix?
      description: |
        Give us the issue number that this Pull Request fixes.
      placeholder: ex. #14
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: |
        Please include a quick summary of the changes.
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Tests
      description: |
        If relevant, please list and explained the tests you've written.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have performed a self-review of my own code
          required: true
        - label: I have made corresponding changes to the documentation
          required: true
        - label: I have commented my code, particularly in hard-to-understand areas
          required: true
