# SPDX-FileCopyrightText: © 2023 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT
#
# Ignore everything.
**

# Except the following.
!src
!LICENSE.md
!pyproject.toml
!poetry.lock
!README.md

# Filter unwanted files from included folders.
**/__pycache__
**.py[cod]
