# Set strict to true to turn warnings into errors to catch warnings within CI.
strict: true
theme:
  name: material
  # By default, fonts are pulled from Google on the Internet. To support
  # offline usage, this is disabled.
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/math-integral-box
    # GitHub specific.
    repo: fontawesome/brands/github
  favicon: static/math-integral-box.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - autoref
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
extra_css:
  - static/stylesheets/extra.css
  - static/stylesheets/mkdocstring.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RomainBrault/python-whiteprint
plugins:
  - search
  - offline:
      enabled: !ENV [MKDOCS_MATERIAL_OFFLINE, false]
  - section-index
  - mkdocstrings:
      handlers:
        python:
          path: [../src]
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          options:
            show_if_no_docstring: true
            show_signature_annotations: true
  # Autodoc configuration.
  # https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  # This plugin is used to validate URLs (including anchors).
  - htmlproofer:
      # This is not enabled by default because this requires network I/O, so it
      # is inherently not exactly reproducible. For larger projects, this can
      # also slow local build times.
      validate_external_urls: !ENV [HTMLPROOFER_VALIDATE_EXTERNAL_URLS, false]
      raise_error: True
watch:
  # Watch src/ directory to reload on changes to docstrings for mkdocstrings
  # plugin.
  - src
site_name: Python Whiteprint
copyright: Copyright &copy; 2018-2023 Romain Brault, John Hagen
# GitHub Specific Configuration.
repo_name: python-whiteprint
repo_url: https://github.com/RomainBrault/python-whiteprint
edit_uri: edit/master/docs/user_guide/docs/
nav:
  - User Guide: index.md
  - Contributor Guide: CONTRIBUTING.md
  - License: LICENSE.md
  - Contributor Covenant Code of Conduct: CODE_OF_CONDUCT.md
  - Code Reference: reference/
  - Dependencies: DEPENDENCIES.md
