{% include "jinja_template/license_header.yml.j2" %}

name: Labeler

on:
  push:
    branches: ["main"]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run Labeler
        uses: actions/labeler@v4
        with:
          sync-labels: true
