{% include "jinja_template/license_header.yml.j2" %}

name: Tests

env:
  PYTHON_VERSION: "{{target_python_version}}"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: ${{'{{'}} matrix.session {{'}}'}} ${{'{{'}} matrix.python {{'}}'}} / ${{'{{'}} matrix.os {{'}}'}}
    runs-on: ${{'{{'}} matrix.os {{'}}'}}
    strategy:
      fail-fast: false
      matrix:
        include:
{%-for i in range(target_python_version.split('.')[1] | int, 12)%}
          - { python: "3.{{i}}", os: "ubuntu-latest", session: "pip-audit" }
{%endfor-%}
{%-for i in range(target_python_version.split('.')[1] | int, 12)%}
          - { python: "3.{{i}}", os: "ubuntu-latest", session: "pre-commit" }
{%endfor-%}
{%-for i in range(target_python_version.split('.')[1] | int, 12)%}
          - { python: "3.{{i}}", os: "ubuntu-latest", session: "test" }
{%endfor-%}

    env:
      NOXSESSION: ${{'{{'}} matrix.session {{'}}'}}
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{'{{'}} matrix.python {{'}}'}}
        uses: actions/setup-python@v4.5.0
        id: setup-python
        with:
          python-version: ${{'{{'}} matrix.python {{'}}'}}
          check-latest: true

      - name: Upgrade python environment
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry rich
          nox --version

      - name: Compute pre-commit cache key
        if: matrix.session == 'pre-commit'
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import os
          import sys

          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = "${{'{{'}} runner.os {{'}}'}}-{}-{}-pre-commit".format(python, digest[:8])

          with open(os.environ["GITHUB_OUTPUT"], mode="w") as github_output:
              print("name=result::{}".format(result), file=github_output)

      - name: Restore pre-commit cache
        uses: actions/cache@v3
        if: matrix.session == 'pre-commit'
        with:
          path: ~/.cache/pre-commit
          key: ${{'{{'}} steps.pre-commit-cache.outputs.result {{'}}'}}-${{'{{'}} hashFiles('.pre-commit-config.yaml') {{'}}'}}
          restore-keys: |
            ${{'{{'}} steps.pre-commit-cache.outputs.result {{'}}'}}-"

      - name: Run Nox
        with:
          WHITEPRINT_TEST_GITHUB_TOKEN: "${{'{{'}} secrets.WHITEPRINT_TEST_GITHUB_TOKEN {{'}}'}}"
        run: |
          nox --force-color --force-python="${{'{{'}} steps.setup-python.outputs.python-path {{'}}'}}"
          [ ! -f .coverage ] || mv .coverage .coverage.${{'{{'}} matrix.python {{'}}'}}

      - name: Upload coverage data
        if: always() && matrix.session == 'test'
        uses: "actions/upload-artifact@v3"
        with:
          name: coverage-data
          path: ".coverage.*"

      - name: Upload documentation
        if: matrix.session == 'docs-check-urls'
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        id: setup-python
        with:
          python-version: ${{'{{'}} env.PYTHON_VERSION {{'}}'}}
          check-latest: true

      - name: Upgrade python environment
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry rich
          nox --version

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Combine coverage data and display human readable report
        run: |
          nox --force-color --session=coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.2
