name: Pages

env:
  PYTHON_VERSION: "3.11"

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Build documentation & check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4.5.0
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry typeguard rich
          nox --version

      - name: Build documentation
        run: nox --force-color --session=docs-check-urls

      - name: Publish Docs
        run: nox --force-color --session=docs-github-pages
