# SPDX-FileCopyrightText: 2023 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT

name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  pr-triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  pr-size:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          xs_label: "size/XS"
          xs_max_size: "10"
          s_label: "size/S"
          s_max_size: "100"
          m_label: "size/M"
          m_max_size: "500"
          l_label: "size/L"
          l_max_size: "1000"
          xl_label: "size/XL"
          fail_if_xl: "false"
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines. Please make
            sure you are NOT addressing multiple issues with one PR. Note this
            PR might be rejected due to its size.
          github_api_url: "api.github.com"
          files_to_ignore: |
            "*.lock"
            "docs/*"
            "*.md"
